name: ProxyKicker
main: org.s4x8.bukkit.proxykicker.ProxyKicker
authors: [socram8888, hypertechHD]
version: 1.5
permissions:
  proxykicker.bypass:
    default: op
    description: Skips proxy check